CREATE TABLE `ACCOMMODATION_CLASS` (
  `ACCOMMODATION_CLASS_ID` varchar(20) COLLATE latin1_general_cs NOT NULL,
  `PARENT_CLASS_ID` varchar(20) COLLATE latin1_general_cs DEFAULT NULL,
  `DESCRIPTION` varchar(255) COLLATE latin1_general_cs DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime DEFAULT NULL,
  `CREATED_STAMP` datetime DEFAULT NULL,
  `CREATED_TX_STAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`ACCOMMODATION_CLASS_ID`),
  KEY `ACCOMM_CLASS_PAR` (`PARENT_CLASS_ID`),
  KEY `ACCMMDN_CLS_TXSTMP` (`LAST_UPDATED_TX_STAMP`),
  KEY `ACCMMDN_CLS_TXCRTS` (`CREATED_TX_STAMP`),
  CONSTRAINT `ACCOMM_CLASS_PAR` FOREIGN KEY (`PARENT_CLASS_ID`) REFERENCES `ACCOMMODATION_CLASS` (`ACCOMMODATION_CLASS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs;